[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.61.0"
RUBY_VERSION = "2.6.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.61.0"

[[redirects]]
  from = "https://georgia-techno.netlify.app/*"
  to = "https://www.georgiatechnologies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/download_file/view/6/173"
  to = "https://www.georgiatechnologies.com/applications/Employment_Application.pdf"
  status = 301
  force = true

[[redirects]]
  from = "https://www.georgiatechnologies.com/remote-support/"
  to = "http://www.georgiatechnologies.com/remote-support/"
  status = 301
  force = true